name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Setup JDK'
        uses: 'actions/setup-java@v3'
        with:
          distribution: 'temurin'
          java-version: 8
          cache: maven

      - name: Maven Build
        run: mvn package

      - name: 'Upload PixelMOTD Jar ☁'
        uses: 'actions/upload-artifact@v4'
        with:
          name: Jar Plugin
          path: ./target/OmegaPixelMOTD*
          retention-days: 30